swagger: '2.0'

# Document metadata
info:
 version: "0.0.1"
 title: Example Photo Service
 
 # URL data
host: api.example.com
basePath: /photo
schemes:
- https
  
# Endpoints
paths:
 # Photo albums
 /album:
  # Get one or more albums
   get:
   # Query parameters
    parameters:
     # Starting date
      - name: start
        in: query
        required: false
        type: string
        
     # Ending date
      - name: end 
        in: query
        required: false
        type: string
       
  # Incomplete responses
    responses:
   # response code
     200:
      description: Succesful response
    
    
 # Photo albums
 /album/{id}:
  # Get one or more albums
   get:
   # Query parameters
    parameters:
     # Starting date
      - name: id
        in: path
        required: true
        type: string
        
     # Ending date
      - name: Access-level 
        in: header
        required: false
        type: string
       
  # Incomplete responses
    responses:
   # response code
     200:
      description: Succesful response
    
    
